name: HydriusJoin
version: '${project.version}'
main: net.hydrius.hydriusjoin.HydriusJoin
api-version: '1.13'
authors: [flrp]
description: Plugin that does stuff on join/leave for Hydrius Network
website: flrp.dev, hydrius.net
depend:
  - PlaceholderAPI
